CREATE TABLE IF NOT EXISTS users(
  id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL, email VARCHAR(100));
CREATE TABLE IF NOT EXISTS products(
  id INT PRIMARY KEY, name VARCHAR(100), category VARCHAR(50), color VARCHAR(30),
  price DECIMAL(10,2), stock INT, rating DECIMAL(2,1), description VARCHAR(500), image_url VARCHAR(300));
CREATE TABLE IF NOT EXISTS cart(
  id INT AUTO_INCREMENT PRIMARY KEY, user_id INT, product_id INT, quantity INT DEFAULT 1,
  UNIQUE KEY uq(user_id, product_id));
CREATE TABLE IF NOT EXISTS orders(
  id INT AUTO_INCREMENT PRIMARY KEY, user_id INT, total DECIMAL(10,2),
  name_on_card VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
